name: Continuos deployment 

on:
  push:
    branches: [main]
env:
  AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"

jobs: 
  test-secrets:
     runs-on: ubuntu-latest

     steps:  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Secret Names by Prefix
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            prod*   
      
      - name: Atribuir valores aos segredos às variáveis de ambiente
        run: |
          echo "PROD_TESTE=${{ steps.secrets.outputs.prod-test }}" >> $GITHUB_ENV
         
     
      - name: Check if env variable is set after fetching secrets
        run: if [ -z ${PROD_TESTE+x} ]; then echo "PROD_TESTE is unset"; else echo "PROD_TESTE is set to '$PROD_TESTE'"; fi

      - name: test
        run: echo 